<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ZN\\XML\\' => array($vendorDir . '/znframework/package-xml'),
    'ZN\\Validation\\' => array($vendorDir . '/znframework/package-validation'),
    'ZN\\Storage\\' => array($vendorDir . '/znframework/package-storage'),
    'ZN\\Shopping\\' => array($vendorDir . '/znframework/package-shopping'),
    'ZN\\Services\\' => array($vendorDir . '/znframework/package-services'),
    'ZN\\Security\\' => array($vendorDir . '/znframework/package-security'),
    'ZN\\Response\\' => array($vendorDir . '/znframework/package-response'),
    'ZN\\Request\\' => array($vendorDir . '/znframework/package-request'),
    'ZN\\Remote\\' => array($vendorDir . '/znframework/package-remote'),
    'ZN\\Protection\\' => array($vendorDir . '/znframework/package-protection'),
    'ZN\\Prompt\\' => array($vendorDir . '/znframework/package-prompt'),
    'ZN\\Payment\\' => array($vendorDir . '/znframework/package-payment'),
    'ZN\\Pagination\\' => array($vendorDir . '/znframework/package-pagination'),
    'ZN\\Language\\' => array($vendorDir . '/znframework/package-language'),
    'ZN\\Image\\' => array($vendorDir . '/znframework/package-image'),
    'ZN\\Hypertext\\' => array($vendorDir . '/znframework/package-hypertext'),
    'ZN\\Helpers\\' => array($vendorDir . '/znframework/package-helpers'),
    'ZN\\Generator\\' => array($vendorDir . '/znframework/package-generator'),
    'ZN\\Filesystem\\' => array($vendorDir . '/znframework/package-filesystem'),
    'ZN\\EventHandler\\' => array($vendorDir . '/znframework/package-event-handler'),
    'ZN\\Email\\' => array($vendorDir . '/znframework/package-email'),
    'ZN\\DateTime\\' => array($vendorDir . '/znframework/package-datetime'),
    'ZN\\Database\\' => array($vendorDir . '/znframework/package-database'),
    'ZN\\DataTypes\\' => array($vendorDir . '/znframework/package-datatypes'),
    'ZN\\Cryptography\\' => array($vendorDir . '/znframework/package-cryptography'),
    'ZN\\Crontab\\' => array($vendorDir . '/znframework/package-crontab'),
    'ZN\\Console\\' => array($vendorDir . '/znframework/package-console'),
    'ZN\\Compression\\' => array($vendorDir . '/znframework/package-compression'),
    'ZN\\Comparison\\' => array($vendorDir . '/znframework/package-comparison'),
    'ZN\\Captcha\\' => array($vendorDir . '/znframework/package-captcha'),
    'ZN\\Cache\\' => array($vendorDir . '/znframework/package-cache'),
    'ZN\\Buffering\\' => array($vendorDir . '/znframework/package-buffering'),
    'ZN\\Authorization\\' => array($vendorDir . '/znframework/package-authorization'),
    'ZN\\Authentication\\' => array($vendorDir . '/znframework/package-authentication'),
    'ZN\\' => array($vendorDir . '/znframework/package-zerocore'),
);
