<?php return array(
    'root' => array(
        'name' => 'znframework/custom-edition',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => NULL,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'znframework/custom-edition' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => NULL,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-authentication' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '58c793262ad2e80d0747f563c266442bfa4e33e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-authentication',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-authorization' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '4bb39a373e183c837bd35331b7cc253ea7c72d66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-authorization',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-buffering' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'a21a0a74ab8bd9b6f755c4d4bb1dd15e279f8582',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-buffering',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-cache' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'e1b7c3c56eadf8748d6bc6f2f716ef91cdfd50f2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-captcha' => array(
            'pretty_version' => '8.22.0',
            'version' => '8.22.0.0',
            'reference' => '0a08c9cc81ca64c9e7b3024ec33b408c9047be73',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-captcha',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-comparison' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'bece3ff1772f3a1f02e17d56e45085ce5cb3c252',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-comparison',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-compression' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'bf6bde7e37028c8ea2a4bac684ac25e42aab522e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-compression',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-console' => array(
            'pretty_version' => '8.24.0',
            'version' => '8.24.0.0',
            'reference' => 'f8b245a3e763718d779f9641d53904000208c46e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-crontab' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '86a4b9bbe528a3a4ddb47e8dc13f62f3d42933dd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-crontab',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-cryptography' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'e1b60bb99752f2940a9633faf0a7c05cd936b92d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-cryptography',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-database' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '1caf8673e9b49a9bb8c18243c3c90cf7dcd93e04',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-database',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-datatypes' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '6adc6ea9eb935fbf3c9fcc6081c1d225ddd5ed03',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-datatypes',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-datetime' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '0336b3fdd5e4dfd8281688d7410fba6bd0fcb86c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-datetime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-email' => array(
            'pretty_version' => '8.24.1',
            'version' => '8.24.1.0',
            'reference' => '75addf6a69c264a523f416e750b32ca7e1ed5234',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-email',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-event-handler' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '4ef8410c4c49754cbc6a402ddd2427e152c0eeba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-event-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-filesystem' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'efe5dc57cda2d473e8e59b35882f40b2306bc2ac',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-generator' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'b4e051e9f12c04515ac0e0360956854fa9328f7a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-generator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-helpers' => array(
            'pretty_version' => '8.22.0',
            'version' => '8.22.0.0',
            'reference' => 'e9aa2d4a83a438c69ff1c625c661ccc26674dcdd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-helpers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-hypertext' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '2e2defe2c16ba6a5c837bcb1aa33fa2d0d1d56e9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-hypertext',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-image' => array(
            'pretty_version' => '8.22.0',
            'version' => '8.22.0.0',
            'reference' => '0738dbe5d039626f2c045c1ee4586c638964212d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-image',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-language' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'a78aa6f68748542525d82805745b74bdeafa1088',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-language',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-pagination' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '752c205cb8c5ef4043d0c55160a6a95d99d6e419',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-pagination',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-payment' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '8deef7a0d8874ab9d720096e5b58d1cd2d69c078',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-payment',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-prompt' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '86e66b203c7d955f383bf570d469b033779bf3e1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-prompt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-protection' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'ad726282767b09edbaf16e06473bca0c35e0e2b2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-protection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-remote' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '397430bb354897c54de6d741c2f6c4b712b16e6a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-remote',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-request' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '153a0fb8b985cb8ac2ddbb2fdd2ecef8fc2c7434',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-request',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-response' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'd8f9c0795853636db8d8d1a89c49d65041b07399',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-response',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-security' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '569bd89baccacf2a3e18fd37f0a339246e003ba3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-security',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-services' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'a4a05463af05f7996f4a26b239392e258b8d510b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-services',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-shopping' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'c77c86aebfaa3b5f2d51ab6962c772f78e1e8908',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-shopping',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-storage' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'c42012e89d63268fe8214a44b8ab8b978610ee8b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-storage',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-validation' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => '16f02077c978e7fdd784645727693d91b91ed9d7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-validation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-xml' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'f2de99f43c475cd261713d173815c1c401c90eb9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-xml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'znframework/package-zerocore' => array(
            'pretty_version' => '8.21.0',
            'version' => '8.21.0.0',
            'reference' => 'd8bf5c931458d828867905205dbb07c5c5f2452b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../znframework/package-zerocore',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
