<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit39d6436dbce8afc7ada435c1a8ad4577
{
    public static $prefixLengthsPsr4 = array (
        'Z' => 
        array (
            'ZN\\XML\\' => 7,
            'ZN\\Validation\\' => 14,
            'ZN\\Storage\\' => 11,
            'ZN\\Shopping\\' => 12,
            'ZN\\Services\\' => 12,
            'ZN\\Security\\' => 12,
            'ZN\\Response\\' => 12,
            'ZN\\Request\\' => 11,
            'ZN\\Remote\\' => 10,
            'ZN\\Protection\\' => 14,
            'ZN\\Prompt\\' => 10,
            'ZN\\Payment\\' => 11,
            'ZN\\Pagination\\' => 14,
            'ZN\\Language\\' => 12,
            'ZN\\Image\\' => 9,
            'ZN\\Hypertext\\' => 13,
            'ZN\\Helpers\\' => 11,
            'ZN\\Generator\\' => 13,
            'ZN\\Filesystem\\' => 14,
            'ZN\\EventHandler\\' => 16,
            'ZN\\Email\\' => 9,
            'ZN\\DateTime\\' => 12,
            'ZN\\Database\\' => 12,
            'ZN\\DataTypes\\' => 13,
            'ZN\\Cryptography\\' => 16,
            'ZN\\Crontab\\' => 11,
            'ZN\\Console\\' => 11,
            'ZN\\Compression\\' => 15,
            'ZN\\Comparison\\' => 14,
            'ZN\\Captcha\\' => 11,
            'ZN\\Cache\\' => 9,
            'ZN\\Buffering\\' => 13,
            'ZN\\Authorization\\' => 17,
            'ZN\\Authentication\\' => 18,
            'ZN\\' => 3,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ZN\\XML\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-xml',
        ),
        'ZN\\Validation\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-validation',
        ),
        'ZN\\Storage\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-storage',
        ),
        'ZN\\Shopping\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-shopping',
        ),
        'ZN\\Services\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-services',
        ),
        'ZN\\Security\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-security',
        ),
        'ZN\\Response\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-response',
        ),
        'ZN\\Request\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-request',
        ),
        'ZN\\Remote\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-remote',
        ),
        'ZN\\Protection\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-protection',
        ),
        'ZN\\Prompt\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-prompt',
        ),
        'ZN\\Payment\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-payment',
        ),
        'ZN\\Pagination\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-pagination',
        ),
        'ZN\\Language\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-language',
        ),
        'ZN\\Image\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-image',
        ),
        'ZN\\Hypertext\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-hypertext',
        ),
        'ZN\\Helpers\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-helpers',
        ),
        'ZN\\Generator\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-generator',
        ),
        'ZN\\Filesystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-filesystem',
        ),
        'ZN\\EventHandler\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-event-handler',
        ),
        'ZN\\Email\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-email',
        ),
        'ZN\\DateTime\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-datetime',
        ),
        'ZN\\Database\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-database',
        ),
        'ZN\\DataTypes\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-datatypes',
        ),
        'ZN\\Cryptography\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-cryptography',
        ),
        'ZN\\Crontab\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-crontab',
        ),
        'ZN\\Console\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-console',
        ),
        'ZN\\Compression\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-compression',
        ),
        'ZN\\Comparison\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-comparison',
        ),
        'ZN\\Captcha\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-captcha',
        ),
        'ZN\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-cache',
        ),
        'ZN\\Buffering\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-buffering',
        ),
        'ZN\\Authorization\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-authorization',
        ),
        'ZN\\Authentication\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-authentication',
        ),
        'ZN\\' => 
        array (
            0 => __DIR__ . '/..' . '/znframework/package-zerocore',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit39d6436dbce8afc7ada435c1a8ad4577::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit39d6436dbce8afc7ada435c1a8ad4577::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit39d6436dbce8afc7ada435c1a8ad4577::$classMap;

        }, null, ClassLoader::class);
    }
}
